file_path : ../Intelligence/tools/teacher/links.txt
base_dir : ../Intelligence/tools/teacher
name : teacher_knowledge_base
chunk_size : 200
chunk_overlap : 75


# pca
n_components : 15
whiten : False

# clustering
# eps : 0.5
# min_samples : 3
# metric : manhattan
min_cluster_size : 3
cluster_selection_epsilon : 0.001