retrieval:
  instance_attr:
    alpha: 0.7
    similarity_top_k: 10

response_synthesis:
  response_tone: helpful assisstant with caring and positive tone
  instance_attr:
    response_mode: refine
    structured_answer_filtering: False
    verbose: True
    use_async: False
    streaming: False