#!/bin/bash

echo "Running lint check on pre-commit..."
cd web
if npx lint-staged; then
  echo "Linting successful. Proceeding with commit..."
else
  echo "Linting failed. Please fix the errors and try again."
  exit 1
fi